#!/bin/bash
if [ -d "$1" ] ; then
    NOTEBOOK_PATH=$1
else
    NOTEBOOK_PATH="`pwd`/notebooks";
fi

if [ -z "$2" ] ; then
    HOST="0.0.0.0"
else
    HOST=$2
fi


docker run -d -v $NOTEBOOK_PATH:/home/ipy/ipynotebooks:rw -p $HOST:8888:8888 -p $HOST:23:22 ipython 
